import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { chromium } from 'playwright';
const server = spawn('npm', ['run', 'dev:web', '--', '--host', '127.0.0.1', '--port', '5192', '--strictPort'], { stdio: 'ignore' });
let browser;
try {
 browser = await chromium.launch();
 const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, locale: 'es-ES', timezoneId: 'Europe/Madrid' });
 await page.route('**/api/**', (route) => route.fulfill({ json: { providers: {} } }));
 for (let i = 0; ; i++) { try { await page.goto('http://127.0.0.1:5192'); break; } catch (error) { if (i >= 20) throw error; await new Promise((resolve) => setTimeout(resolve, 250)); } }
 await page.locator('.project-tile').first().waitFor();
 await page.evaluate(async () => { const { useWorkspace } = await import('/src/store/useWorkspace.ts'); const state = useWorkspace.getState(); useWorkspace.setState({ activeView: 'gym', workouts: state.workouts.map((workout, index) => ({ ...workout, startedAt: new Date(Date.now() - index * 86400000).toISOString() })) }); });
 await page.getByRole('heading', { name: 'Gimnasio', exact: true }).waitFor();
 await page.screenshot({ path: '/tmp/notehub-gym-desktop.png' });
 assert.equal(await page.locator('.gym-tabs').count(), 0);
 assert.ok(await page.getByRole('button', { name: /^Empezar rutina/ }).count());
 assert.equal(await page.locator('.gym-stats').count(), 0);
 await page.getByRole('button', { name: 'Nueva rutina' }).click();
 const dialog = page.getByRole('dialog', { name: 'Editar rutina' });
 await dialog.getByLabel('Nombre de rutina').fill('Mi sesión');
 await dialog.getByLabel('Ejercicio para rutina').selectOption('incline-db');
 await dialog.getByRole('button', { name: '', exact: true }).click();
 await dialog.getByRole('button', { name: 'Guardar', exact: true }).click();
 const routine = page.locator('.gym-routines .gym-routine-row').filter({ has: page.getByRole('heading', { name: 'Mi sesión' }) });
 await routine.getByRole('button', { name: 'Empezar rutina Mi sesión' }).click();
 await page.getByLabel('Peso serie 1', { exact: true }).fill('32');
 await page.getByLabel('Repeticiones serie 1', { exact: true }).fill('10');
 await page.getByRole('checkbox', { name: 'Completar serie 1', exact: true }).click();
 assert.ok(await page.getByText(/Descanso · 1:/).count());
 await page.getByRole('button', { name: 'Añadir serie' }).click();
 assert.equal(await page.getByRole('checkbox').count(), 4);
 await page.evaluate(async () => (await import('/src/store/useWorkspace.ts')).useWorkspace.setState({ activeView: 'calendar' }));
 await page.locator('.home-layout').waitFor();
 await page.evaluate(async () => (await import('/src/store/useWorkspace.ts')).useWorkspace.setState({ activeView: 'gym' }));
 assert.equal(await page.getByLabel('Peso serie 1', { exact: true }).inputValue(), '32');
 assert.equal(await page.getByRole('checkbox', { name: 'Completar serie 1', exact: true }).getAttribute('aria-checked'), 'true');
 await page.setViewportSize({ width: 375, height: 900 });
 await page.screenshot({ path: '/tmp/notehub-gym-session-mobile.png', fullPage: true });
 assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
 await page.getByRole('button', { name: 'Terminar y guardar' }).click();
 const saved = await page.evaluate(async () => (await import('/src/store/useWorkspace.ts')).useWorkspace.getState().workouts.at(-1));
 assert.equal(saved.title, 'Mi sesión');
 assert.equal(saved.exercises[0].sets[0].weight, 32);
 assert.equal(saved.exercises[0].sets[0].completed, true);
 assert.ok(saved.endedAt);
 assert.equal(await page.evaluate(() => localStorage.getItem('notehub-gym-draft-v1')), null);
 await page.getByRole('button', { name: 'Volver a entrenar', exact: false }).click();
 await page.screenshot({ path: '/tmp/notehub-gym-mobile.png', fullPage: true });
 console.log('Gym passed: routine creation, logging, draft survival, rest timer, save, summaries and mobile width.');
} finally { await browser?.close(); server.kill('SIGTERM'); }
