import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { SettingsView } from './SettingsView';
import { cloudSync } from '../../sync/cloudSync';
vi.mock('./WorkspaceBackups', () => ({ WorkspaceBackups: () => null }));
vi.mock('../../native/NativeSettings', () => ({ NativeSettings: () => null }));
vi.mock('../../hooks/useTheme', () => ({ useTheme: () => ({ theme: 'light', followsSystem: true, chooseTheme: vi.fn(), useSystemTheme: vi.fn() }) }));
vi.mock('../../ai/keyVault', () => ({ hasProviderKey: vi.fn(async () => false) }));
vi.mock('../../ai/provider', () => ({ getActiveProvider: () => 'openai', getProviderStatus: vi.fn(async () => ({})) }));
vi.mock('../../sync/cloudSync', () => ({ cloudSync: { configured: true, status: vi.fn(async () => ({ configured: true, connected: false })), signInWithPassword: vi.fn(), sendEmailCode: vi.fn() } }));
afterEach(() => { cleanup(); vi.clearAllMocks(); });
it('opens password sign-in first, prevents duplicate requests, and lets the user select email links', async () => {
  let reject!: (error: Error) => void;
  vi.mocked(cloudSync.signInWithPassword).mockImplementation(() => new Promise((_, fail) => { reject = fail; }));
  render(<SettingsView />);
  await waitFor(() => expect(screen.getByLabelText('Sync password')).toBeInTheDocument());
  fireEvent.change(screen.getByLabelText('Sync email'), { target: { value: 'person@example.com' } });
  fireEvent.change(screen.getByLabelText('Sync password'), { target: { value: 'password' } });
  fireEvent.click(screen.getByRole('button', { name: 'Sign in' }));
  expect(screen.getByRole('button', { name: 'Connecting…' })).toBeDisabled();
  expect(cloudSync.signInWithPassword).toHaveBeenCalledOnce();
  reject(new Error('Invalid login credentials'));
  await screen.findByText('Invalid login credentials');
  fireEvent.click(screen.getByRole('button', { name: 'Use email link' }));
  expect(screen.queryByLabelText('Sync password')).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: 'Send sign-in email' }));
  await screen.findByLabelText('Email link or code');
  expect(cloudSync.sendEmailCode).toHaveBeenCalledWith('person@example.com');
});
