// swift-tools-version: 5.9
// Generated by scripts/prepare-ios.mjs after cap sync.
import PackageDescription
let package = Package(name: "CapApp-SPM", platforms: [.iOS(.v17)],
 products: [.library(name: "CapApp-SPM", targets: ["CapApp-SPM"])],
 targets: [
  .binaryTarget(name: "Capacitor", path: "Frameworks/Capacitor.xcframework"),
  .binaryTarget(name: "Cordova", path: "Frameworks/Cordova.xcframework"),
  .target(name: "CapApp-SPM", dependencies: ["Capacitor", "Cordova"])
 ])
