import { mkdir, readFile, writeFile, access } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';
// Keep official binaries locally: Xcode's binary-package download cache can retain corrupt archives.
const version = JSON.parse(await readFile('node_modules/@capacitor/ios/package.json', 'utf8')).version;
if (version !== '8.5.2') throw new Error('Update the verified Capacitor checksums before changing the native version.');
const root = resolve('ios/App/CapApp-SPM/Frameworks');
await mkdir(root, { recursive: true });
for (const [name, checksum] of [['Capacitor', '134c65a8bd30bfaa8ccb158d78142fa7231bf3f472e4a5d808c5fbed90fd4c75'], ['Cordova', '57ff2c8f1e5dcd8d4379ac3cccde1407d81ccd575347dc2aff4f72272b8794a1']]) {
  try { await access(`${root}/${name}.xcframework/Info.plist`); continue; } catch { /* Fetch on first setup. */ }
  const response = await fetch(`https://github.com/ionic-team/capacitor-swift-pm/releases/download/${version}/${name}.xcframework.zip`);
  if (!response.ok) throw new Error(`Cannot download ${name}: ${response.status}`);
  const data = Buffer.from(await response.arrayBuffer());
  if (createHash('sha256').update(data).digest('hex') !== checksum) throw new Error(`Invalid ${name} checksum`);
  const archive = `${root}/${name}.zip`;
  await writeFile(archive, data);
  execFileSync('unzip', ['-oq', archive, '-d', root]);
}
await writeFile('ios/App/CapApp-SPM/Package.swift', `// swift-tools-version: 5.9
// Generated by scripts/prepare-ios.mjs after cap sync.
import PackageDescription
let package = Package(name: "CapApp-SPM", platforms: [.iOS(.v17)],
 products: [.library(name: "CapApp-SPM", targets: ["CapApp-SPM"])],
 targets: [
  .binaryTarget(name: "Capacitor", path: "Frameworks/Capacitor.xcframework"),
  .binaryTarget(name: "Cordova", path: "Frameworks/Cordova.xcframework"),
  .target(name: "CapApp-SPM", dependencies: ["Capacitor", "Cordova"])
 ])
`);
console.log('Native frameworks ready (official binaries, SHA-256 verified).');
