create table if not exists public.workspace_operations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  operation_id uuid not null unique,
  client_id uuid not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists workspace_operations_user_created_idx
  on public.workspace_operations (user_id, created_at);

alter table public.workspace_operations enable row level security;

create policy "users read own workspace operations"
  on public.workspace_operations for select
  using (auth.uid() = user_id);

create policy "users insert own workspace operations"
  on public.workspace_operations for insert
  with check (auth.uid() = user_id);

alter publication supabase_realtime add table public.workspace_operations;

create table if not exists public.workspace_snapshots (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.workspace_snapshots enable row level security;
create policy "users read own workspace snapshot" on public.workspace_snapshots for select using (auth.uid() = user_id);
create policy "users insert own workspace snapshot" on public.workspace_snapshots for insert with check (auth.uid() = user_id);
create policy "users update own workspace snapshot" on public.workspace_snapshots for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
